/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroMotoristaRouteImport } from './routes/cadastro.motorista'
import { Route as CadastroEmpresaRouteImport } from './routes/cadastro.empresa'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroMotoristaRoute = CadastroMotoristaRouteImport.update({
  id: '/cadastro/motorista',
  path: '/cadastro/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroEmpresaRoute = CadastroEmpresaRouteImport.update({
  id: '/cadastro/empresa',
  path: '/cadastro/empresa',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro/empresa': typeof CadastroEmpresaRoute
  '/cadastro/motorista': typeof CadastroMotoristaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro/empresa': typeof CadastroEmpresaRoute
  '/cadastro/motorista': typeof CadastroMotoristaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro/empresa': typeof CadastroEmpresaRoute
  '/cadastro/motorista': typeof CadastroMotoristaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/cadastro/empresa' | '/cadastro/motorista'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/cadastro/empresa' | '/cadastro/motorista'
  id: '__root__' | '/' | '/auth' | '/cadastro/empresa' | '/cadastro/motorista'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CadastroEmpresaRoute: typeof CadastroEmpresaRoute
  CadastroMotoristaRoute: typeof CadastroMotoristaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/motorista': {
      id: '/cadastro/motorista'
      path: '/cadastro/motorista'
      fullPath: '/cadastro/motorista'
      preLoaderRoute: typeof CadastroMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/empresa': {
      id: '/cadastro/empresa'
      path: '/cadastro/empresa'
      fullPath: '/cadastro/empresa'
      preLoaderRoute: typeof CadastroEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CadastroEmpresaRoute: CadastroEmpresaRoute,
  CadastroMotoristaRoute: CadastroMotoristaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
