/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmbarcadorPublicarRouteImport } from './routes/embarcador.publicar'
import { Route as EmbarcadorFretesRouteImport } from './routes/embarcador.fretes'
import { Route as CadastroMotoristaRouteImport } from './routes/cadastro.motorista'
import { Route as CadastroEmpresaRouteImport } from './routes/cadastro.empresa'
import { Route as EmbarcadorFreteIdRouteImport } from './routes/embarcador.frete.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbarcadorPublicarRoute = EmbarcadorPublicarRouteImport.update({
  id: '/embarcador/publicar',
  path: '/embarcador/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbarcadorFretesRoute = EmbarcadorFretesRouteImport.update({
  id: '/embarcador/fretes',
  path: '/embarcador/fretes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroMotoristaRoute = CadastroMotoristaRouteImport.update({
  id: '/cadastro/motorista',
  path: '/cadastro/motorista',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroEmpresaRoute = CadastroEmpresaRouteImport.update({
  id: '/cadastro/empresa',
  path: '/cadastro/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbarcadorFreteIdRoute = EmbarcadorFreteIdRouteImport.update({
  id: '/embarcador/frete/$id',
  path: '/embarcador/frete/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro/empresa': typeof CadastroEmpresaRoute
  '/cadastro/motorista': typeof CadastroMotoristaRoute
  '/embarcador/fretes': typeof EmbarcadorFretesRoute
  '/embarcador/publicar': typeof EmbarcadorPublicarRoute
  '/embarcador/frete/$id': typeof EmbarcadorFreteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro/empresa': typeof CadastroEmpresaRoute
  '/cadastro/motorista': typeof CadastroMotoristaRoute
  '/embarcador/fretes': typeof EmbarcadorFretesRoute
  '/embarcador/publicar': typeof EmbarcadorPublicarRoute
  '/embarcador/frete/$id': typeof EmbarcadorFreteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cadastro/empresa': typeof CadastroEmpresaRoute
  '/cadastro/motorista': typeof CadastroMotoristaRoute
  '/embarcador/fretes': typeof EmbarcadorFretesRoute
  '/embarcador/publicar': typeof EmbarcadorPublicarRoute
  '/embarcador/frete/$id': typeof EmbarcadorFreteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cadastro/empresa'
    | '/cadastro/motorista'
    | '/embarcador/fretes'
    | '/embarcador/publicar'
    | '/embarcador/frete/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cadastro/empresa'
    | '/cadastro/motorista'
    | '/embarcador/fretes'
    | '/embarcador/publicar'
    | '/embarcador/frete/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/cadastro/empresa'
    | '/cadastro/motorista'
    | '/embarcador/fretes'
    | '/embarcador/publicar'
    | '/embarcador/frete/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CadastroEmpresaRoute: typeof CadastroEmpresaRoute
  CadastroMotoristaRoute: typeof CadastroMotoristaRoute
  EmbarcadorFretesRoute: typeof EmbarcadorFretesRoute
  EmbarcadorPublicarRoute: typeof EmbarcadorPublicarRoute
  EmbarcadorFreteIdRoute: typeof EmbarcadorFreteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embarcador/publicar': {
      id: '/embarcador/publicar'
      path: '/embarcador/publicar'
      fullPath: '/embarcador/publicar'
      preLoaderRoute: typeof EmbarcadorPublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embarcador/fretes': {
      id: '/embarcador/fretes'
      path: '/embarcador/fretes'
      fullPath: '/embarcador/fretes'
      preLoaderRoute: typeof EmbarcadorFretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/motorista': {
      id: '/cadastro/motorista'
      path: '/cadastro/motorista'
      fullPath: '/cadastro/motorista'
      preLoaderRoute: typeof CadastroMotoristaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/empresa': {
      id: '/cadastro/empresa'
      path: '/cadastro/empresa'
      fullPath: '/cadastro/empresa'
      preLoaderRoute: typeof CadastroEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embarcador/frete/$id': {
      id: '/embarcador/frete/$id'
      path: '/embarcador/frete/$id'
      fullPath: '/embarcador/frete/$id'
      preLoaderRoute: typeof EmbarcadorFreteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CadastroEmpresaRoute: CadastroEmpresaRoute,
  CadastroMotoristaRoute: CadastroMotoristaRoute,
  EmbarcadorFretesRoute: EmbarcadorFretesRoute,
  EmbarcadorPublicarRoute: EmbarcadorPublicarRoute,
  EmbarcadorFreteIdRoute: EmbarcadorFreteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
